name: 0.1.$(Date:yyMMdd)$(Rev:.r)

parameters:
- name: buildConfiguration
  displayName: 'Build Configuration'
  type: string
  default: 'Release'
  values:
  - 'Release'
  - 'Debug'
- name: buildPlatform
  displayName: 'Build Platform'
  type: string
  default: 'Any CPU'
  values:
  - 'Any CPU'
  - 'x64'
  - 'x86'

trigger:
   batch: True
   branches:
     include:
     - 'feature/*'
     - 'main'

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'

steps:
- task: NuGetAuthenticate@1

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    packageType: sdk
    version: '8.0.x'
    performMultiLevelLookup: true